[options]
# Keep enterprise path first if you add an enterprise checkout:
# addons_path = enterprise,custom_addons,addons
addons_path = custom_addons,addons

# HTTP Settings
http_interface = 127.0.0.1
xmlrpc_port = 8069

# Database Settings
db_host = localhost
db_port = 5432
db_user = odoo
db_password = admin@123
admin_passwd = admin@123
db_name = odoo
dbfilter = ^odoo$
